apiVersion: v1
kind: Service
metadata:
  name: claper-svc-headless
spec:
  ports:
    - port: 4369
      targetPort: epmd
      protocol: TCP
      name: epmd
  selector:
    app: claper
  clusterIP: None