apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: claper-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  tls:
  - hosts:
    - claper.co
    secretName: claper-tls
  rules:
    - host: claper.co
      http:
        paths:
          - pathType: Prefix
            path: "/"
            backend:
              service:
                name: claper-svc
                port:
                  number: 80
