apiVersion: v1
kind: ServiceAccount
metadata:
  name: sa-claper
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: role-claper
rules:
  - apiGroups:
      - ""
    resources:
      - endpoints
    verbs:
      - list
      - get
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: rb-claper
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: role-claper
subjects:
  - kind: ServiceAccount
    name: sa-claper